source = $HOME/.config/hypr/colors/hyprlock-colors.conf
source = $HOME/.config/hypr/colors/current-wallpaper.conf

background {
    monitor =
    path = $current_wallpaper
    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 4
    blur_passes = 3 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $purple
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 240
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $white
    font_size = 112
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, 110
    halign = center
    valign = center
}

# Seconds
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%S") </big></b>"
    color = $white
    font_size = 30
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 110, 50
    halign = center
    valign = center
}

# Today
label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $color7
    font_size = 22
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 30
    halign = center
    valign = center
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $color7
    font_size = 18
    font_family = JetBrainsMono Nerd Font 10

    position = 0, 0
    halign = center
    valign = center
}