require("variables")
require("colors/dracula")

require("hyprland/monitors")
require("hyprland/execs")
require("hyprland/input")
require("hyprland/keybinds")
require("hyprland/workspaces")
require("hyprland/gestures")
require("hyprland/env")
require("hyprland/decoration")
require("hyprland/animations")
require("hyprland/rules")
require("hyprland/general")
require("hyprland/scrolling")
