#!/usr/bin/env bash
# cachyos-compat.sh
# Applies CachyOS-kernel-safe overrides on top of the universal tune scripts'
# persisted config. Idempotent and safe to re-run. Does NOT install the kernel
# (use install-cachyos-kernel.sh for that) - it only guarantees that nothing in
# the current system config conflicts with the CachyOS kernel.
#
# Why this exists:
#   The CachyOS kernel differs from mainline Arch in a few ways:
#     - bfq I/O scheduler is NOT built in (mainline tune scripts reference it)
#     - BBR is built in, and fq+bbr is the CachyOS networking recommendation
#     - THP should stay at madvise (CachyOS recommendation)
#
# What it does:
#   1. Rewrites the udev I/O scheduler rules WITHOUT bfq:
#        NVMe        -> none
#        rotational  -> mq-deadline (or best available: deadline -> none)
#   2. Ensures sysctl has fq + bbr (applied last, overrides tune defaults)
#   3. Ensures /etc/kernel/cmdline has transparent_hugepage=madvise and
#      regenerates all UKIs (mkinitcpio -P / dracut --regenerate-all)
#   4. Verifies the applied state (and the CachyOS UKI if already installed)
#
# Usage:
#   sudo ./cachyos-compat.sh

set -uo pipefail

# ---------- colors & output ----------
if [[ -t 1 ]]; then
  C_OK=$'\033[1;32m'; C_W=$'\033[1;33m'; C_E=$'\033[1;31m'; C_B=$'\033[1;34m'; C_0=$'\033[0m'
else
  C_OK=''; C_W=''; C_E=''; C_B=''; C_0=''
fi
ok()   { printf '%s[✓]%s %s\n' "$C_OK" "$C_0" "$*"; }
fail() { printf '%s[✗]%s %s\n' "$C_E" "$C_0" "$*"; }
warn() { printf '%s[!]%s %s\n' "$C_W" "$C_0" "$*"; }
head() { printf '\n%s== %s ==%s\n' "$C_B" "$*" "$C_0"; }

# ---------- root ----------
if [[ $EUID -ne 0 ]]; then
  echo "Re-running with sudo..."
  exec sudo --preserve-env=HOME "$0" "$@"
fi

UDEV_FILE="/etc/udev/rules.d/60-ioschedulers.rules"
SYSCTL_FILE="/etc/sysctl.d/zz-cachyos-compat.conf"
KCMDLINE="/etc/kernel/cmdline"
BACKUP_DIR="/var/lib/perf-tune-backup"
TS="$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"

# =====================================================================
head "1. I/O scheduler rules (no bfq - CachyOS kernels don't ship it)"

# Detect which schedulers the current kernel provides (CachyOS lacks bfq).
AVAIL_SCHEDS=""
for d in /sys/block/*; do
  [[ -f "$d/queue/scheduler" ]] || continue
  AVAIL_SCHEDS="$AVAIL_SCHEDS $(cat "$d/queue/scheduler")"
done
# Candidate list deliberately excludes bfq.
HDD_SCHED=""
for s in mq-deadline deadline none; do
  if grep -qw "$s" <<<"$AVAIL_SCHEDS"; then HDD_SCHED="$s"; break; fi
done

if [[ -f "$UDEV_FILE" ]] && grep -q bfq "$UDEV_FILE"; then
  cp -a "$UDEV_FILE" "$BACKUP_DIR/ioschedulers.bfq.$TS"
  chmod 600 "$BACKUP_DIR/ioschedulers.bfq.$TS"
  warn "backed up bfq-containing rules -> $BACKUP_DIR/ioschedulers.bfq.$TS"
fi

{
  printf '# Generated by cachyos-compat.sh (CachyOS-kernel-safe, no bfq)\n'
  printf '# NVMe (multi-queue) -> none scheduler, 256 KiB readahead\n'
  printf 'ACTION=="add|change", KERNEL=="nvme[0-9]*n[0-9]*", ATTR{queue/scheduler}="none", ATTR{queue/read_ahead_kb}="256"\n'
  if [[ -n "$HDD_SCHED" ]]; then
    printf '# Rotational disks -> %s scheduler (CachyOS-safe), 8 MiB readahead\n' "$HDD_SCHED"
    printf 'ACTION=="add|change", KERNEL=="sd[a-z]*|vd[a-z]*|mmcblk*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="%s", ATTR{queue/read_ahead_kb}="8192"\n' "$HDD_SCHED"
  else
    printf '# No HDD scheduler available on this kernel; rule omitted\n'
  fi
} > "$UDEV_FILE"
udevadm control --reload-rules >/dev/null 2>&1
udevadm trigger --action=change --subsystem-match=block >/dev/null 2>&1 || true
ok "udev rules rewritten without bfq (rotational -> ${HDD_SCHED:-none})"

# =====================================================================
head "2. sysctl: fq qdisc + bbr congestion control (CachyOS recommendation)"

# Applied last (zz- prefix) so these win over the tune scripts' defaults.
cat > "$SYSCTL_FILE" <<'EOF'
# Generated by cachyos-compat.sh
# CachyOS networking recommendation: fq qdisc + BBR
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF

if sysctl net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -qw bbr; then
  if sysctl -p "$SYSCTL_FILE" >/dev/null 2>&1; then
    ok "sysctl applied: fq + bbr"
  else
    fail "sysctl -p $SYSCTL_FILE failed (check /etc/sysctl.conf or .d ordering)"
  fi
else
  warn "bbr not available on the running kernel yet - config written, takes effect on CachyOS"
fi

# =====================================================================
head "3. Kernel cmdline: transparent_hugepage=madvise + UKI regeneration"

if [[ ! -f "$KCMDLINE" ]]; then
  warn "no $KCMDLINE (systemd-boot cmdline file) - nothing to align"
else
  cp -a "$KCMDLINE" "$BACKUP_DIR/cmdline.cachyos.$TS" 2>/dev/null
  chmod 600 "$BACKUP_DIR/cmdline.cachyos.$TS" 2>/dev/null
  CURRENT="$(cat "$KCMDLINE")"
  ADDED=""
  if ! grep -qw -- "transparent_hugepage=madvise" <<<"$CURRENT"; then
    CURRENT="$CURRENT transparent_hugepage=madvise"
    ADDED=" transparent_hugepage=madvise"
  fi
  CURRENT="$(echo "$CURRENT" | sed -E 's/^ +//; s/ +/ /g; s/ +$//')"
  if [[ -n "$ADDED" ]]; then
    echo "$CURRENT" > "$KCMDLINE"
    ok "cmdline updated, added:$ADDED"
  else
    ok "cmdline already contains transparent_hugepage=madvise"
  fi
fi

if command -v mkinitcpio >/dev/null && [[ -n "$(find /etc/mkinitcpio.d -maxdepth 1 -name '*.preset' 2>/dev/null)" ]]; then
  if mkinitcpio -P >/dev/null 2>&1; then
    ok "mkinitcpio regenerated all UKIs"
  else
    fail "mkinitcpio -P failed"
  fi
elif command -v dracut >/dev/null; then
  if dracut --regenerate-all >/dev/null 2>&1; then
    ok "dracut regenerated all images"
  else
    fail "dracut --regenerate-all failed"
  fi
else
  warn "no mkinitcpio/dracut found - UKIs not regenerated"
fi

# =====================================================================
head "4. Verification"

V=0
check() { if [[ "$2" -eq 0 ]]; then ok "$1"; else fail "$1"; V=1; fi; }

QDISK="$(sysctl -n net.core.default_qdisc 2>/dev/null)"
CC="$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null)"
check "qdisc = fq (got '$QDISK')" "$([[ "$QDISK" == "fq" ]]; echo $?)"
check "tcp_congestion_control = bbr (got '$CC')" "$([[ "$CC" == "bbr" ]]; echo $?)"

if grep -q bfq "$UDEV_FILE"; then
  check "udev rules contain no bfq" 1
else
  check "udev rules contain no bfq" 0
fi

if [[ -f "$KCMDLINE" ]] && grep -qw -- "transparent_hugepage=madvise" "$KCMDLINE"; then
  check "cmdline has transparent_hugepage=madvise" 0
else
  check "cmdline has transparent_hugepage=madvise" 1
fi

# UKI carries the param (if a UKI exists)
mapfile -t _UKIS < <(find /boot/EFI/Linux -maxdepth 1 -name '*.efi' -type f 2>/dev/null | sort)
if [[ ${#_UKIS[@]} -gt 0 ]] && command -v objcopy >/dev/null; then
  _UKI="$(ls -1t "${_UKIS[@]}" | head -1)"
  _cmd="$(objcopy -O binary --only-section=.cmdline "$_UKI" /tmp/cachyos-uki-cmd-$$ 2>/dev/null && tr -d '\0' < /tmp/cachyos-uki-cmd-$$; rm -f /tmp/cachyos-uki-cmd-$$)"
  if grep -qw -- "transparent_hugepage=madvise" <<<"$_cmd"; then
    check "UKI $(basename "$_UKI") carries transparent_hugepage=madvise" 0
  else
    check "UKI $(basename "$_UKI") carries transparent_hugepage=madvise" 1
  fi
elif [[ ${#_UKIS[@]} -eq 0 ]]; then
  warn "no UKIs found yet - run install-cachyos-kernel.sh first, then re-run this script"
fi
unset _UKIS

head "DONE"
cat <<EOF
  Applied CachyOS-kernel-safe overrides:
    - $UDEV_FILE (no bfq)
    - $SYSCTL_FILE (fq + bbr, applied last)
    - $KCMDLINE (transparent_hugepage=madvise)
  Backups: $BACKUP_DIR/ (ioschedulers.bfq.$TS, cmdline.cachyos.$TS)

  REBOOT required for the cmdline/udev changes to fully apply.
EOF

exit "$V"
