require("variables")
require("colors/colors")

require("hyprland/monitors")
require("hyprland/execs")
require("hyprland/input")
require("hyprland/keybinds")
require("hyprland/workspaces")
require("hyprland/env")
require("hyprland/decoration")
require("hyprland/animations")
require("hyprland/rules")
require("hyprland/general")
require("hyprland/border-colors")
require("hyprland/scrolling")
