# System control
windowrule = float true, match:class foot, match:title nmtui
windowrule = size 60% 70%, match:class foot, match:title nmtui
windowrule = center 1, match:class foot, match:title nmtui
windowrule = float true, match:class blueman-manager
windowrule = float true, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = size 60% 70%, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser
windowrule = center 1, match:class org\.pulseaudio\.pavucontrol|yad-icon-browser

# Steam
windowrule = rounding 10, match:class steam
windowrule = float true, match:title Friends List, match:class steam

windowrule = float true, match:class nwg-look
windowrule = size 50% 60%, match:class nwg-look
windowrule = center 1, match:class nwg-look

# Dialogs
windowrule = float true, match:title (Select|Open)( a)? (File|Folder)(s)?
windowrule = float true, match:title File (Operation|Upload)( Progress)?
windowrule = float true, match:title .* Properties
windowrule = float true, match:title Export Image as PNG
windowrule = float true, match:title GIMP Crash Debug
windowrule = float true, match:title Save As
windowrule = float true, match:title Library

# Games (Steam, Lutris/Wine, Gamescope)
windowrule = opaque true, match:class (steam_app_(default|[0-9]+))|gamescope
windowrule = immediate true, match:class (steam_app_(default|[0-9]+))|gamescope  # Allow tearing for games
windowrule = idle_inhibit always, match:class (steam_app_(default|[0-9]+))|gamescope  # Always idle inhibit when playing a game

# Ugh xwayland popups
windowrule = no_dim true, match:xwayland 1, match:title win[0-9]+
windowrule = no_shadow true, match:xwayland 1, match:title win[0-9]+
windowrule = rounding 10, match:xwayland 1, match:title win[0-9]+


# Notification
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0
layerrule = match:namespace swaync-notification-window, ignore_alpha 0
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5
layerrule = match:namespace swaync-control-center, animation slide left

# Top bar
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0
layerrule = match:namespace swayosd, blur on
layerrule = match:namespace swayosd, ignore_alpha 0

# App launcher
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0
layerrule = match:namespace rofi, animation slide bottom

# Special workspaces
windowrule = workspace special:music, match:class feishin|Spotify|Supersonic|Cider|com.github.th_ch.youtube_music|Plexamp
windowrule = workspace special:communication, match:class discord|equibop|vesktop|whatsapp