# Desktop Apps
exec-once = awww-daemon
exec-once = waybar
exec-once = swaync

#Cursor
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme $gtktheme
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"

# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent

# Hypridle
exec-once = hypridle

# Autostart apps
#exec-once = solaar --window=hide
#exec-once = steam -silent
#exec-once = element-desktop --hidden
#exec-once = discord --start-minimized
#exec-once = opendeck --hide
#exec-once = localsend --hidden
#exec-once = heroic