monitor = DP-1, 3440x1440@165, 0x0, 1, bitdepth, 10
monitor = DP-2, 2560x1440@165, 3440x-730, 1, transform, 3, bitdepth, 10

misc {
    vfr = true
    vrr = 1
}

workspace = 1, monitor:DP-1, persistent:true
workspace = 2, monitor:DP-2, persistent:true

workspace = 3, monitor:DP-1, persistent:true
workspace = 4, monitor:DP-2, persistent:true

workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2

workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-2

workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-2